#image:
#  tag: 10.5.1
existingSecret: gracedb-test-secrets
rootUser:
  #password: dummy 
  forcePassword: false
db:
  user: gracedb
  #password: dummy
  name: gracedb
persistence:
  enabled: true
  size: 20Gi
service:
  type: NodePort
  #clusterIP: None
securityContext:
  runAsUser: 0
  fsGroup: 0
replicaCount: 3
#livenessProbe:
#  enabled: false
#readinessProbe: 
#  enabed: false
#initdbScriptsConfigMap: cleanup-pv
 
  
