apiVersion: v1
kind: PersistentVolume
metadata:
  name: gracedb-test-pv-ha
  namespace: gracedb-test
spec:
  storageClassName: "cinder"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: gracedb-test
    name: cinder-gracedb-test-ha
  hostPath:
    path: "/mnt/gdb-test-ha"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cinder-gracedb-test-ha
  namespace: gracedb-test
spec:
  storageClassName: "cinder"
  accessModes:
  - ReadWriteMany
  resources:
   requests:
     storage: 1Gi
