# Insert your secrets here 
# and rename the file to kustomization.yaml
secretGenerator:
- name: gracedb-test-secrets
  namespace: gracedb-test
  literals:
  - db-password=<changeme>
  - db-root-password=<changeme>
  - dj-secret-key=<changeme>
  - lvalert-password=<changeme>
generatorOptions:
  disableNameSuffixHash: true
