# Insert your secrets here 
# and rename the file to kustomization.yaml
secretGenerator:
- name: gracedb-test-secrets
  namespace: gracedb-test
  literals:
  - db-password=<changeme>
  - db-root-password=<changeme>
  - dj-secret-key=<changeme>
  - lvalert-password=<changeme>
  - mariadb-galera-mariabackup-password=<changeme>
  # should be equal to db-password and db-root-password
  # (TODO: use only one set of variables)
  - mariadb-password=<changeme>
  - mariadb-root-password=<changeme>
generatorOptions:
  disableNameSuffixHash: true
