apiVersion: v1
kind: PersistentVolume
metadata:
  name: gracedb-test-mysql-pv
  namespace: gracedb-test
spec:
  storageClassName: "cinder"
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gracedb-test-mysql-pvc
  namespace: gracedb-test
spec:
  storageClassName: "cinder"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
